### ISSUE TITLE
redirect to http://sogo/

### ISSUE THREAD

**Issue by dolanor** [julienfastre/docker-sogo#3]
Hi,

I tried to launch it through the `docker-compose.yml` file and using the image (not building one).
I can access the service on port http://myip:8080, but then it redirect me to http://sogo/
I didn't see anything in the sogo.conf to tune this parameter. What should I do?

**Comment by julienfastre** [comment]
Hi.

This is not a problem in sogo configuration, but in nginx config. We should take into account the port in the `nginx.conf` file. 

If you run sogo under port 80 or 443, this should not happen. The nginx.conf file is for test only, not for production.

**Comment by dolanor** [comment]
So you mean that if I put 

```diff
    ports:
-      - "8080:80"
+      - "80:80"
```
in the nginx.conf, it should work ?

**Comment by dolanor** [comment]
Ok, so I already tried that, but it didn't work.
Now I replaced every `$server_name` in the `nginx.conf` file by the IP address of my server (didn't bother to have domain name for it yet) and it then worked.
I will try to figure out which parameters made that (I suspect the `x-webobjects-server-name` )

**Comment by julienfastre** [comment]
Could you send your new `nginx.conf` ? I would be happy if I could improve this issue.

**Comment by dolanor** [comment]
Grrrr

Of course, reverting the `nginx.conf` file now works if I just do as you said (put 80:80 instead of 8080:80) but I'm really confident I tried that before changing the nginx file…
Anyway, now it's fixed for me. I will just add those headers to my `Caddyfile` so I don't have to have double proxies and I will get rid of the nginx.conf.

Well, thank you for your support and the image :)

**Comment by julienfastre** [comment]
It is a pleasure :-)
